services:
  sync:
    image: wazoplatform/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  ui:
    image: wazo-ui-test
    ports:
      - "9296"
    expose:
      - "9296"
    volumes:
      - "../..:/usr/src/wazo-ui"
      - "./etc/wazo-ui/conf.d/default.yml:/etc/wazo-ui/conf.d/50-default.yml"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/opt/venv/lib/python3.7/site-packages/xivo"

  auth:
    image: wazoplatform/wazo-auth-mock
    ports:
      - "9497"

  browser:
    image: selenium/standalone-firefox
    ports:
      - "4444"
    shm_size: '2GB'
